baseURL = "https://tmwprojects.github.io/Blog/"
languageCode = 'en-us'
title = 'HackSide $'
theme = 'github.com/serkodev/holy'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
